import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ResourcesService } from '../../services/resources.service';
import { ConfirmService } from '../../services/confirm.service';
import { ToastService } from '../../services/toast.service';

@Component({
    selector: 'app-coach-hub',
    standalone: true,
    imports: [CommonModule, FormsModule],
    templateUrl: './coach-hub.component.html',
    styleUrl: './coach-hub.component.css'
})
export class CoachHubComponent implements OnInit {
    resources: any[] = [];
    filteredResources: any[] = [];
    filterType: string = 'All';
    showForm: boolean = false;
    selectedFileName: string = '';
    selectedFile: File | null = null;

    newResource: any = {
        title: '',
        type: 'Pitch',
        content: '',
        tags: ''
    };

    types = ['Pitch', 'CV', 'Question', 'Note', 'File'];

    constructor(
        private resourcesService: ResourcesService,
        private confirmService: ConfirmService,
        private toastService: ToastService
    ) { }

    ngOnInit() {
        this.loadResources();
    }

    loadResources() {
        this.resourcesService.getAll().subscribe(data => {
            this.resources = data;
            this.filterResources();
        });
    }

    filterResources() {
        if (this.filterType === 'All') {
            this.filteredResources = this.resources;
        } else {
            this.filteredResources = this.resources.filter(r => r.type === this.filterType);
        }
    }

    onFileSelected(event: any) {
        const file = event.target.files[0];
        if (file) {
            this.selectedFile = file;
            this.selectedFileName = file.name;
            this.newResource.title = this.newResource.title || file.name;
            this.newResource.type = file.type.includes('pdf') ? 'CV' : 'File';
        }
    }

    addResource() {
        if (!this.newResource.title) return;

        let payload;
        if (this.selectedFile) {
            const formData = new FormData();
            formData.append('file', this.selectedFile);
            formData.append('title', this.newResource.title);
            formData.append('type', this.newResource.type);
            formData.append('tags', this.newResource.tags || '');
            // content is auto-generated by backend for files
            payload = formData;
        } else {
            payload = this.newResource;
        }

        this.resourcesService.create(payload).subscribe(() => {
            this.loadResources();
            this.showForm = false;
            this.selectedFileName = '';
            this.selectedFile = null;
            this.newResource = { title: '', type: 'Pitch', content: '', tags: '' };
        });
    }

    async deleteResource(id: number) {
        if (await this.confirmService.confirm('Delete this resource?', 'Delete Resource')) {
            this.resourcesService.delete(id).subscribe(() => {
                this.toastService.show('Resource deleted', 'success');
                this.loadResources();
            });
        }
    }

    getIcon(type: string): string {
        switch (type) {
            case 'CV': return '📄';
            case 'Pitch': return '🎤';
            case 'Question': return '❓';
            case 'Note': return '📝';
            case 'File': return '📁';
            default: return '📌';
        }
    }

    isFilePath(content: string): boolean {
        return !!(content && content.startsWith('/uploads/'));
    }
}
